### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/fedora-packages#406] opened 2018-11-04 10:48 UTC
Just search for `enki`.

![image](https://user-images.githubusercontent.com/8781107/47963116-55f96c00-e038-11e8-8103-38e1af7926af.png)

**Comment by steaksauce-** [comment] 2018-11-04 15:19
Might be if the package is available in the default repo and EPEL, but I'm not sure.

**Comment by Zlopez** [comment] 2018-11-05 14:45
Another example `libssh2` shows 2 results, `curl` shows 4 results and so on.

I wasn't able to find the pattern for this.

**Comment by Zlopez** [comment] 2018-11-05 14:58
Looking at the sources, it looks like the issue is coming from here https://github.com/fedora-infra/fedora-packages/blob/master/fedoracommunity/search/index.py#L200

PDC is probably returning the duplicate results.

**Comment by abitrolly** [comment] 2018-11-06 03:44
https://pdc.fedoraproject.org/rest_api/v1/global-components/?name=curl returns one result.

My bet is that there are some problem with database indexing. Like index key is not unique or contains colums that change for some reason for the same product version.

**Comment by steaksauce-** [comment] 2018-11-11 02:07
I cannot reproduce the behavior on the version 4.2.0 tag. Not sure when the release for this is though.

**Comment by abitrolly** [comment] 2018-11-16 18:17
@steaksauce- do you use the same DB as production?

**Comment by steaksauce-** [comment] 2018-11-16 18:56
> @steaksauce- do you use the same DB as production?

tbh, I don't know (probably not though).

Whatever `docker-compose` is giving me in the devel folder

**Comment by cverna** [comment] 2018-11-21 15:07
I have been working on https://github.com/fedora-infra/fedora-search to replace the xapian backend of fedora-packages. 
I think having an independent service and the db stored in postgresql will make it easier to investigate and fix this kind of problems

**Comment by abitrolly** [comment] 2018-11-21 19:44
And if the issue is repeated with the same backend, how do you debug it?

Also, how do you share PostreSQL DB?

Also, are you sure that PostreSQL stemmers are good for full text search?

**Comment by abitrolly** [comment] 2018-11-29 03:03
> Postresql full text search has been around for a while now, and it seems a viable solution for simple search application like this one.

I couldn't find any serious comparison yet, but there are references that PostgreSQL supports stemming, so I have to believe you that it is good. :)

**Comment by cverna** [comment] 2019-07-26 18:55
Closing this ticket

**Closed by cverna** 2019-07-26 18:55 UTC
