### ISSUE TITLE
Sources tab gives nothing

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/fedora-packages#364] opened 2018-05-15 06:52 UTC
1. Go to https://apps.fedoraproject.org/packages/ranger/
2. Click `Changelog` tab to ensure it loads
3. Click `Sources` tab to see that nothing happens, not even error

No error in console, but in network debugging there is 500 server error
![image](https://user-images.githubusercontent.com/8781107/40041086-7f06a086-5825-11e8-8976-1d70cba7ac5a.png)

The URL also changes to https://apps.fedoraproject.org/packages/ranger/sources/ and following the link also gives 404. Request URL from network debug pane https://apps.fedoraproject.org/packages/_w/package_sources?subpackage_of=&package_name=ranger

**Comment by pypingou** [comment] 2018-05-15 07:37
I'm going to close this one as a duplicate of https://github.com/fedora-infra/fedora-packages/issues/329#issuecomment-389062985

**Closed by pypingou** 2018-05-15 07:37 UTC

**Comment by abitrolly** [comment] 2018-05-15 08:07
Yes, but this one is so very good. I spent so much time creating it. =) Can you get some comment with status update on the issue? What is going on there? Sentry report?
