### ISSUE TITLE
packages missing from search

### ISSUE THREAD

**Issue by alex-tee** [fedora-infra/fedora-packages#437] opened 2020-03-29 15:17 UTC
hi,
the package guile22 cannot be found online https://src.fedoraproject.org/rpms/guile https://apps.fedoraproject.org/packages/s/guile however it shows up when you search through dnf.

**Comment by genodeftest** [comment] 2020-04-21 17:59
It also affects other packages, e.g. `quiterss`.

**Comment by genodeftest** [comment] 2020-04-21 18:00
Duplicate of #432

**Comment by cverna** [comment] 2020-04-21 18:26
Closing as duplicate of #432

**Closed as completed** 2020-04-21 18:26 UTC
