### ISSUE TITLE
No info in mdapi for lots of packages

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/fedora-packages#411] opened 2019-01-06 23:37 UTC
From https://pagure.io/fedora-infrastructure/issue/7471

Sorry for opening this again (it was supposed to be fixed in #7291), but lots of our packages are still missing information on the packages application. Examples:

- https://apps.fedoraproject.org/packages/python-efel
- https://apps.fedoraproject.org/packages/python-nitime
- https://apps.fedoraproject.org/packages/python-pynwb
- https://apps.fedoraproject.org/packages/python-mne-bids
- https://apps.fedoraproject.org/packages/python-pybids
- https://apps.fedoraproject.org/packages/python-dipy
- https://apps.fedoraproject.org/packages/python-petlink
- https://apps.fedoraproject.org/packages/python-nilearn
- https://apps.fedoraproject.org/packages/python-fsleyes
- https://apps.fedoraproject.org/packages/python-brian2
- https://apps.fedoraproject.org/packages/genesis
- https://apps.fedoraproject.org/packages/python-PyLEMS
- https://apps.fedoraproject.org/packages/python-nineml

nirik said mdapi does have the info, but the packages app isn't picking it up: https://pagure.io/fedora-infrastructure/issue/7471#comment-548244

Could someone have a look please?

**Comment by cverna** [comment] 2019-01-07 10:58
So the problem is that there is no info for these packages in mdapi for the f29 branch for example https://apps.fedoraproject.org/mdapi/f29/srcpkg/python-efel

And these packages don't seems to be in f29, I am not sure why the packages does not look at the packages in rawhide, i ll check that and add another comment here.

**Comment by sanjayankur31** [comment] 2019-01-07 11:16
Uhm, these packages are in F28/F29 also:

- https://src.fedoraproject.org/rpms/python-efel/branches?branchname=master
- https://bodhi.fedoraproject.org/updates/?packages=python-efel

So mdapi has no info for stable branches: back to mdapi bug then?

**Comment by cverna** [comment] 2019-01-07 11:22
> Uhm, these packages are in F28/F29 also:
> 
>     * https://src.fedoraproject.org/rpms/python-efel/branches?branchname=master
> 
>     * https://bodhi.fedoraproject.org/updates/?packages=python-efel
> 
> 
> So mdapi has no info for stable branches: back to mdapi bug then?

I ll investigate the mdapi side before we decide to open a ticket other there :smile:

**Comment by cverna** [comment] 2019-01-07 19:33
So I have opened https://pagure.io/pungi/issue/1105, let see how that goes :smile:

**Comment by sanjayankur31** [comment] 2019-01-09 17:14
@cverna I see the pagure ticket was closed. Is this a simple fix (I hope!)?

**Comment by cverna** [comment] 2019-01-09 18:40
@sanjayankur31 we are currently waiting on the next update compose run to happen, that should create the files needed by mdapi.
Then I can reindex packages and we should have the info available

**Comment by sanjayankur31** [comment] 2019-01-14 18:00
@cverna did the indexing thing work? These packages are still missing :(

**Comment by cverna** [comment] 2019-01-14 18:46
@sanjayankur31 sorry for not updating the ticket but https://apps.fedoraproject.org/mdapi/f29/srcpkg/python-efel is still giving a 404. I need to look deeper at mdapi code and I have not had time to do that today.

**Comment by sanjayankur31** [comment] 2019-01-14 18:50
Sure, no worries. Thanks again :)

**Comment by Lyude** [comment] 2019-07-10 17:46
Hi! I was told on https://pagure.io/fedora-infrastructure/issue/7974#comment-581356 that I should note here that one of the packages I maintain, igt-gpu-tools, doesn't seem to have any information on the packages application either

**Comment by cverna** [comment] 2019-07-26 18:57
So all these packages are now working. Closing this ticket.

**Closed by cverna** 2019-07-26 18:57 UTC

**Comment by QuLogic** [comment] 2019-09-08 04:41
This seems broken again. All the packages I'm looking at today have no mdapi data, and I'm pretty sure they used to.

**Comment by chkr-private** [comment] 2020-02-08 10:48
Same here, e.g. https://apps.fedoraproject.org/packages/s/scummvm can't be found. Please re-open the bug report.
