### ISSUE TITLE
SCM link broken on https://apps.fedoraproject.org/packages/XXX

### ISSUE THREAD

**Issue by junghans** [fedora-infra/fedora-packages#285] opened 2017-08-21 12:18 UTC
On https://apps.fedoraproject.org/packages/XXX, the SCM link points to https://pkgs.fedoraproject.org/cgit/XXX.git, whichs get forwarded to the non-existing https://src.fedoraproject.org/XXX.git instead of https://src.fedoraproject.org/rpms/XXX.
(Where XXX is any package name.)

**Comment by pypingou** [comment] 2017-08-21 16:14
This is a duplicate of https://github.com/fedora-infra/fedora-packages/issues/282

Thanks for raising it though :)

**Closed by pypingou** 2017-08-21 16:14 UTC
