### ISSUE TITLE
Getting changelog from the API returns empty values on some packages

### ISSUE THREAD

**Issue by axilleas** [fedora-infra/fedora-packages#103] opened 2014-08-05 08:23 UTC
For some packages the changelog is on the web ui but is missing when an API call is made. I didn't report it in [pkgwat.api](https://github.com/fedora-infra/pkgwat.api) since this is an API problem hence affects the output of `pkgwat.api`.

Example: 

<https://apps.fedoraproject.org/packages/rubygem-listen/changelog/> has entries, but 
```python
In [5]: pkg.changelog("rubygem-listen")
Out[5]: 
{u'rows': [],
 u'rows_per_page': 10,
 u'start_row': 0,
 u'total_rows': 0,
 u'visible_rows': 0}
```

The list below are packages I specifically queried:
```
---
- rubygem-listen
- rubygem-origin
- rubygem-cocaine
- rubygem-mongo
- rubygem-timers
- rubygem-dynect_rest
- rubygem-authlogic
- rubygem-ruby-debug19
- rubygem-rgen
- rubygem-openstack-compute
- rubygem-compass
- rubygem-cloudservers
- rubygem-audited-activerecord
- rubygem-archivist
- rubygem-openshift-origin-controller
- rubygem-rugged
- rubygem-icalendar
- rubygem-ruby-openid
- rubygem-newgem
- rubygem-simple_form
- rubygem-linecache19
- rubygem-ci_reporter
- rubygem-activerecord-nulldb-adapter
- rubygem-ruby-debug-base19
- rubygem-scoped_search
- rubygem-rerun
```

**Comment by ralphbean** [comment] 2015-10-17 01:35
Confirmed.  I see rubygem-listen returning results now, but I got nothing back for rubygem-origin.  Not sure of the cause yet.  Will have to add some debugging to see.

**Comment by ralphbean** [comment] 2015-11-20 18:39
OK, I **think** this should be all fixed with the [latest release](http://threebean.org/blog/history-of-fedora-packages/).  Please re-open if you encounter further issues... and thanks so much for your patience.  :)

**Closed by ralphbean** 2015-11-20 18:39 UTC
Labels: API
