### ISSUE TITLE
Bug dropdown does not work in some cases

### ISSUE THREAD

**Issue by rugk** [fedora-infra/fedora-packages#353] opened 2018-03-26 16:55 UTC
STR:
1. Go to https://apps.fedoraproject.org/packages/android-tools/bugs/. Dropdown works.
2. Switch to another tab and fastly switch back to "Bugs".

What happens: Dropdown does not work anymore.

What should happen: Dropdown should always work.

Firefox 59

**Comment by lentzi90** [comment] 2018-05-19 15:41
Also affects Chrome

**Comment by lentzi90** [comment] 2018-05-19 17:03
This seems to be a duplicate of #349

**Closed** 2018-05-19 18:42 UTC
