### ISSUE TITLE
"SCM" link still links to old pkgs.fedoraproject.org cgit interface

### ISSUE THREAD

**Issue by richardfearn** [fedora-infra/fedora-packages#310] opened 2017-11-27 20:24 UTC
e.g. for `rlwrap` URL is https://pkgs.fedoraproject.org/cgit/rlwrap.git but should be https://src.fedoraproject.org/rpms/rlwrap.

**Comment by pypingou** [comment] 2017-11-27 20:27
This is a duplicate of #294

**Closed by pypingou** 2017-11-27 20:27 UTC

**Comment by richardfearn** [comment] 2017-11-27 20:32
Thanks - I didn't include closed tickets in my search :-/
