### ISSUE TITLE
new packages does not appear in search 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#309] opened 2017-11-19 15:26 UTC
https://apps.fedoraproject.org/packages/s/vid.stab  

when https://src.fedoraproject.org/rpms/vid.stab exist 
and https://bodhi.fedoraproject.org/updates/?packages=vid.stab also

**Comment by nirik** [comment] 2017-11-26 22:04
dupe of #229

**Closed by nirik** 2017-11-26 22:04 UTC
