### ISSUE TITLE
TSS2 package missing from Fedora package search

### ISSUE THREAD

**Issue by hcl2014** [fedora-infra/fedora-packages#261] opened 2017-01-17 18:53 UTC
The TSS2 was accepted awhile back (even before another package called "tpm2-tss", which is similar but they are different packages):
https://admin.fedoraproject.org/pkgdb/package/rpms/tss2/

However, It's missing in:
https://apps.fedoraproject.org/packages/

I thought I used to be able to find TSS2 from this site.  Can anyone please look into this?

**Comment by nirik** [comment] 2017-11-26 22:05
dupe of #229

**Closed by nirik** 2017-11-26 22:05 UTC
