### ISSUE TITLE
syncthing package missing

### ISSUE THREAD

**Issue by leoluk** [fedora-infra/fedora-packages#296] opened 2017-09-29 17:29 UTC
The syncthing package is missing from the package viewer even though it's been in the repo for two months: 

https://apps.fedoraproject.org/packages/syncthing

https://bodhi.fedoraproject.org/updates/?packages=syncthing

**Comment by cverna** [comment] 2017-09-29 20:13
Hi thanks for the reports but this is a duplicate of #286. Therefore i am closing this issue

**Closed by cverna** 2017-09-29 20:13 UTC
