### ISSUE TITLE
Fedora Packages website is missing eosrei-emojione-fonts

### ISSUE THREAD

**Issue by mavit** [fedora-infra/fedora-packages#308] opened 2017-11-06 11:48 UTC
I notice that page https://src.fedoraproject.org/rpms/eosrei-emojione-fonts exists, but page https://apps.fedoraproject.org/packages/eosrei-emojione-fonts does not.

**Comment by cverna** [comment] 2017-11-09 12:32
The production version of fedora-packages is currently not updated with the packages available at src.fp.o. I am working on deploying a new version that will slove this issue.

**Comment by nirik** [comment] 2017-11-26 22:04
dupe of #229

**Closed by nirik** 2017-11-26 22:04 UTC
