### ISSUE TITLE
"packages" application is outdated

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/fedora-packages#286] opened 2017-08-23 05:45 UTC
New packages are not available

Ex: https://apps.fedoraproject.org/packages/s/php-pecl-timecop

**Comment by leoluk** [comment] 2017-11-10 15:41
Still broken - can I help somehow?

**Comment by nirik** [comment] 2017-11-26 22:03
duplicate of #229

**Closed by nirik** 2017-11-26 22:03 UTC
